# Weather data generation note
#
# The file data/weather_data_final.csv was generated from NASA POWER daily data
# using district-level latitude/longitude coordinates. It is included in the repository
# as a processed input for HW2. The final modelling datasets are regenerated by
# src/finalize_hw2.py.
